# Generated by Django 4.1.7 on 2023-02-22 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Emenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Phone', models.IntegerField(default=0)),
                ('Email', models.EmailField(max_length=40)),
                ('Date_Check_In', models.DateField()),
                ('Date_Check_Out', models.DateField()),
                ('Adulte', models.IntegerField(default=0)),
                ('Children', models.IntegerField(default=0)),
                ('Note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('Availability', models.IntegerField(default='0')),
                ('hotel_description', models.TextField()),
                ('hotel_image', models.ImageField(upload_to='uploads/')),
                ('price', models.IntegerField()),
                ('emenities', models.ManyToManyField(to='store.emenities')),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.location')),
            ],
        ),
    ]
