# Generated by Django 4.1.7 on 2023-05-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='img',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
