# Generated by Django 4.1.7 on 2023-05-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='img',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
